### ISSUE TITLE
Missing OR Statement means starting prompt doesn't stop.

### ISSUE THREAD

**Issue by BDragisic** [Alfredredbird/alfred#18]
In line 183 of brib.py it contains the following statement:
`    if "" in input1 and inputnum != "":
        test = True`
This statement never evaluates and causes the login prompt to never stop printing ⤷ . It needs changing to OR which solves the issue.

**Comment by Alfredredbird** [comment]
Hey, thanks for the Pull request. However, I have looked into the issue and found that `    if "" in input1 and inputnum != "": test = True`  does get run.  It works by capturing if options such as `-d` and `-t` receive empty input. If you switch it to an OR statement, Alfred gets run no matter what option you enter.

**Comment by Jaypolarnoir** [comment]
Please this is my error
Traceback (most recent call last):
  File "/data/data/com.termux/files/home/alfred/brib.py", line 11, in <module>
    from alive_progress import *
ModuleNotFoundError: No module named 'alive_progress'

**Comment by Jaypolarnoir** [comment]
Please teach me how to solve it am not familiar with Scripting

**Comment by BDragisic** [comment]
You likely need to install the requirements, you can do this with the following command
`pip3 install -r requirements.txt`

**Comment by Alfredredbird** [comment]
> Please this is my error Traceback (most recent call last): File "/data/data/com.termux/files/home/alfred/brib.py", line 11, in from alive_progress import * ModuleNotFoundError: No module named 'alive_progress'

there is an error in the `requirements.txt` file. To fix the error, please run `pip install alive-progress` hope that helps.
